### ISSUE TITLE
I dont understand usage ejample

### ISSUE THREAD

**Issue by Dacio11** [jcageman/d2mapapi#15]
i download visual 2022 but i dont know how to configure, help pls

**Comment by jcageman** [comment]
![image](https://user-images.githubusercontent.com/13038863/155196844-d23d4eb5-41cc-4cde-8c92-9d3becd34318.png)

To run locally edit launchSettings.json like in the screenshot. Use the D2Map.Api project as startup project (right click, set as startup). Hope that clarifies it?

**Comment by Dacio11** [comment]
![Captura de pantalla (1)](https://user-images.githubusercontent.com/82827132/155208098-68669461-8c2c-4651-8f40-1636edad97f5.png)

is correct, what i have to do now?
thanks!

**Comment by jcageman** [comment]
Yes looks good! Note the application is hosted on port 8080

**Comment by Dacio11** [comment]
![Captura de pantalla (2)](https://user-images.githubusercontent.com/82827132/155217014-c154e530-50b5-419b-a058-31c17ba5eaa9.png)

**Comment by jcageman** [comment]
It should be 1.13c and you can modify appsettings.json

**Comment by Dacio11** [comment]
now is 1.13c, i edited appsettings.json, I installed the game in c:\diablo II this time, still same error.

System.Exception
  HResult=0x80131500
  Mensaje = Provided invalid diablo 2 directory: <C:\Diablo II\>
  Origen = D2Map.Core
  Seguimiento de la pila:
   at D2Map.Core.Extensions.CoreExtensions.RegisterCoreServices(IServiceCollection services, IConfiguration config) in C:\Users\PC\Desktop\d2mapapi-1.2\D2Map.Core\Extensions\CoreExtensions.cs:line 15
   at D2Map.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Users\PC\Desktop\d2mapapi-1.2\D2Map.Api\Startup.cs:line 36
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at D2Map.Api.Program.Main(String[] args) in C:\Users\PC\Desktop\d2mapapi-1.2\D2Map.Api\Program.cs:line 16

**Comment by jcageman** [comment]
![image](https://user-images.githubusercontent.com/13038863/155277952-982cce1c-0cce-4f4a-a03a-ad5dba046929.png)

Almost there!

**Comment by Dacio11** [comment]
Yea, now works, but how can i see the map ? 

![Captura de pantalla (4)](https://user-images.githubusercontent.com/82827132/155303214-741553ab-25be-4d0b-8392-b84191196ef7.png)

**Comment by jcageman** [comment]
I haven't build a visualization tool. This only exposes an API (see readme) that returns the data which could be visualized

**Comment by Dacio11** [comment]
and how i can visualize that?

**Comment by jcageman** [comment]
The API response in 1.2 is same as in 1.0
